# How often to save all changed data to file, in ticks (20 ticks = 1 second)
# Changing this value will require a server restart
fileSaveTicks: 72000

# The maximum number of Elytras players can pick up
maxElytras: 2

# The worlds this plugin listens to
worlds:
  - "world_the_end"
