main: me.scyphers.fruitservers.elytralimiter.ElytraLimiter
name: ElytraLimiter
version: 1.0
api-version: 1.17
author: Scyphers
commands:
  elimiter:
    permission: elytralimiter.commands
    description: View the collection for your players island
    usage: "/elimiter [args]"
    aliases: [elytralimiter]

permissions:
  elytralimiter.commands:
    default: op
    description: Ability to use the command
  elytralimiter.commands.reload:
    default: op
    description: reloads the plugin
  elytralimiter.commands.reset:
    default: op
    description: resets a players elytra count
  elytralimiter.override:
    default: op
    description: Allows the player to be ignored for the elytra limit